#Version: 1.0
#Author: T0X1C
Messages:
  OnlyPlayers: "&4&lAnimated&cTablist&c&l+ &8> &7Only players can perform these commands!"
  NoPermissions: "&4&lAnimated&cTablist&c&l+ &8> &7You don't have permissions!"
  ReloadedConfig: "&4&lAnimated&cTablist&c&l+ &8> &7Reloaded config.yml"

#In ticks (20 ticks = 1 second)
UpdateTime: 2
#You can use %n to make a new line
Headers:
  - '&7T'
  - '&7T'
  - '&7Th'
  - '&7Th'
  - '&7Tha'
  - '&7Tha'
  - '&7Than'
  - '&7Than'
  - '&7Thank'
  - '&7Thank'
  - '&7Thanks'
  - '&7Thanks'
  - '&7Thanks f'
  - '&7Thanks f'
  - '&7Thanks fo'
  - '&7Thanks fo'
  - '&7Thanks for'
  - '&7Thanks for'
  - '&7Thanks for u'
  - '&7Thanks for u'
  - '&7Thanks for us'
  - '&7Thanks for us'
  - '&7Thanks for usi'
  - '&7Thanks for usi'
  - '&7Thanks for usin'
  - '&7Thanks for usin'
  - '&7Thanks for using'
  - '&7Thanks for using'
  - '&7Thanks for using &4A'
  - '&7Thanks for using &4A'
  - '&7Thanks for using &4An'
  - '&7Thanks for using &4An'
  - '&7Thanks for using &4Ani'
  - '&7Thanks for using &4Ani'
  - '&7Thanks for using &4Anim'
  - '&7Thanks for using &4Anim'
  - '&7Thanks for using &4Anima'
  - '&7Thanks for using &4Anima'
  - '&7Thanks for using &4Animat'
  - '&7Thanks for using &4Animat'
  - '&7Thanks for using &4Animate'
  - '&7Thanks for using &4Animate'
  - '&7Thanks for using &4Animated'
  - '&7Thanks for using &4Animated'
  - '&7Thanks for using &4Animated&cT'
  - '&7Thanks for using &4Animated&cT'
  - '&7Thanks for using &4Animated&cTa'
  - '&7Thanks for using &4Animated&cTa'
  - '&7Thanks for using &4Animated&cTab'
  - '&7Thanks for using &4Animated&cTab'
  - '&7Thanks for using &4Animated&cTabl'
  - '&7Thanks for using &4Animated&cTabl'
  - '&7Thanks for using &4Animated&cTabli'
  - '&7Thanks for using &4Animated&cTabli'
  - '&7Thanks for using &4Animated&cTablis'
  - '&7Thanks for using &4Animated&cTablis'
  - '&7Thanks for using &4Animated&cTablist'
  - '&7Thanks for using &4Animated&cTablist'
  - '&7Thanks for using &4Animated&cTablist&c&l+'
  - '&7Thanks for using &4Animated&cTablist&c&l+'

#Use can use %n to make a new line
Footers:
  - '&4&m------------------------------'
  - '&4&m------------------------------'
  - '&c&m------------------------------'
  - '&c&m------------------------------'
  - '&4&m------------------------------'
  - '&4&m------------------------------'
  - '&c&m------------------------------'
  - '&c&m------------------------------'